name: face3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=7.5.0
  - scikit-image
  - scikit-learn
  - scipy
  - cython
